--mysql -u root -p

--DROP DATABASE IF EXISTS dblocker;

CREATE DATABASE IF NOT EXISTS dblocker;

USE dblocker;

CREATE TABLE armario (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    secao VARCHAR(3) NOT NULL,
    numero INT NOT NULL,
    local VARCHAR(20),
    andar VARCHAR(5),
    situacao VARCHAR(12) NOT NULL,

    CONSTRAINT uk_secao_numero UNIQUE (secao, numero)

);

CREATE TABLE curso (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    codigo_curso CHAR(2) NOT NULL UNIQUE,
    nome VARCHAR(50) NOT NULL,
    duracao TINYINT(1) NOT NULL

);

CREATE TABLE funcionario (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE,
    senha VARCHAR(45) NOT NULL,
    nome VARCHAR(45) NOT NULL,
    sobrenome VARCHAR(45) NOT NULL,
    funcao VARCHAR(30) NOT NULL,
    privilegio VARCHAR(30) NOT NULL

);

CREATE TABLE aluno (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rm INT NULL UNIQUE,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE,
    senha VARCHAR(45) NOT NULL,
    nome VARCHAR(45) NOT NULL,
    sobrenome VARCHAR(45) NOT NULL

);

CREATE TABLE cursando (

    id_aluno INT NOT NULL,
    id_curso INT NOT NULL,
    modulo TINYINT(1) NOT NULL,
    periodo VARCHAR(10),
    situacao_matricula TINYINT(1),

    CONSTRAINT pk_id_aluno_id_curso PRIMARY KEY (id_aluno, id_curso),

    CONSTRAINT fk_cursando_aluno FOREIGN KEY (id_aluno) REFERENCES aluno(id),
    CONSTRAINT fk_cursando_curso FOREIGN KEY (id_curso) REFERENCES curso(id)

);

CREATE TABLE telefone_funcionario (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    telefone VARCHAR(11) NOT NULL,
    id_funcionario INT NOT NULL,

    CONSTRAINT fk_telefone_funcionario_funcionario FOREIGN KEY (id_funcionario) REFERENCES funcionario(id)

);

CREATE TABLE telefone_aluno (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    telefone VARCHAR(11) NOT NULL,
    id_aluno INT NOT NULL,

    CONSTRAINT fk_telefone_aluno_aluno FOREIGN KEY (id_aluno) REFERENCES aluno(id)

);

CREATE TABLE aluguel (

    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    plano VARCHAR(9) NOT NULL,
    data_locacao DATE NOT NULL,
    situacao_locacao TINYINT(1),
    id_aluno INT NOT NULL,
    id_armario INT NOT NULL,

    CONSTRAINT fk_locacao_aluno FOREIGN KEY (id_aluno) REFERENCES aluno(id),
    CONSTRAINT fk_locacao_armario FOREIGN KEY (id_armario) REFERENCES armario(id)

);

SET AUTOCOMMIT = 0;

INSERT INTO curso (codigo_curso, nome, duracao) VALUES
('C', 'Administração Integral', 6),
('B', 'Nutrição e Dietética Integral', 6),
('D', 'Química Integral', 6),
('L', 'Administração', 3),
('N', 'Nutrição e Dietética', 3),
('Q', 'Química', 3),
('H', 'Desenvolvimento de Sistemas', 3);

INSERT INTO armario (secao, numero, local, andar, situacao) VALUES
('C', 1, 'quimica', '1', 'disponivel'),
('C', 2, 'quimica', '1', 'disponivel'),
('C', 3, 'quimica', '1', 'disponivel'),
('C', 4, 'quimica', '1', 'disponivel'),
('C', 5, 'quimica', '1', 'disponivel'),
('C', 6, 'quimica', '1', 'disponivel'),
('C', 7, 'quimica', '1', 'disponivel'),
('C', 8, 'quimica', '1', 'disponivel'),
('C', 9, 'quimica', '1', 'disponivel'),
('C', 10, 'quimica', '1', 'disponivel'),
('C', 11, 'quimica', '1', 'disponivel'),
('C', 12, 'quimica', '1', 'disponivel'),
('C', 13, 'quimica', '1', 'disponivel'),
('C', 14, 'quimica', '1', 'disponivel'),
('C', 15, 'quimica', '1', 'disponivel'),
('C', 16, 'quimica', '1', 'disponivel'),
('C', 17, 'quimica', '1', 'disponivel'),
('C', 18, 'quimica', '1', 'disponivel'),
('C', 19, 'quimica', '1', 'disponivel'),
('C', 20, 'quimica', '1', 'disponivel'),
('D', 1, 'quimica', '1', 'alugado'),
('D', 2, 'quimica', '1', 'alugado'),
('D', 3, 'quimica', '1', 'alugado'),
('D', 4, 'quimica', '1', 'alugado'),
('D', 5, 'quimica', '1', 'alugado'),
('D', 6, 'quimica', '1', 'alugado'),
('D', 7, 'quimica', '1', 'alugado'),
('D', 8, 'quimica', '1', 'alugado'),
('D', 9, 'quimica', '1', 'alugado'),
('D', 10, 'quimica', '1', 'alugado'),
('D', 11, 'quimica', '1', 'alugado'),
('D', 12, 'quimica', '1', 'alugado'),
('D', 13, 'quimica', '1', 'alugado'),
('D', 14, 'quimica', '1', 'alugado'),
('D', 15, 'quimica', '1', 'alugado'),
('D', 16, 'quimica', '1', 'alugado'),
('D', 17, 'quimica', '1', 'alugado'),
('D', 18, 'quimica', '1', 'alugado'),
('D', 19, 'quimica', '1', 'alugado'),
('D', 20, 'quimica', '1', 'alugado'),
('E', 1, 'quimica', '1', 'disponivel'),
('E', 2, 'quimica', '1', 'disponivel'),
('E', 3, 'quimica', '1', 'disponivel'),
('E', 4, 'quimica', '1', 'disponivel'),
('E', 5, 'quimica', '1', 'disponivel'),
('E', 6, 'quimica', '1', 'disponivel'),
('E', 7, 'quimica', '1', 'disponivel'),
('E', 8, 'quimica', '1', 'disponivel'),
('E', 9, 'quimica', '1', 'disponivel'),
('E', 10, 'quimica', '1', 'disponivel'),
('E', 11, 'quimica', '1', 'disponivel'),
('E', 12, 'quimica', '1', 'disponivel'),
('E', 13, 'quimica', '1', 'disponivel'),
('E', 14, 'quimica', '1', 'disponivel'),
('E', 15, 'quimica', '1', 'disponivel'),
('E', 16, 'quimica', '1', 'disponivel'),
('E', 17, 'quimica', '1', 'disponivel'),
('E', 18, 'quimica', '1', 'disponivel'),
('E', 19, 'quimica', '1', 'disponivel'),
('E', 20, 'quimica', '1', 'disponivel'),
('F', 1, 'quimica', '1', 'indisponivel'),
('F', 2, 'quimica', '1', 'indisponivel'),
('F', 3, 'quimica', '1', 'indisponivel'),
('F', 4, 'quimica', '1', 'indisponivel'),
('F', 5, 'quimica', '1', 'indisponivel'),
('F', 6, 'quimica', '1', 'indisponivel'),
('F', 7, 'quimica', '1', 'indisponivel'),
('F', 8, 'quimica', '1', 'indisponivel'),
('F', 9, 'quimica', '1', 'indisponivel'),
('F', 10, 'quimica', '1', 'indisponivel'),
('F', 11, 'quimica', '1', 'indisponivel'),
('F', 12, 'quimica', '1', 'indisponivel'),
('F', 13, 'quimica', '1', 'indisponivel'),
('F', 14, 'quimica', '1', 'indisponivel'),
('F', 15, 'quimica', '1', 'indisponivel'),
('F', 16, 'quimica', '1', 'indisponivel'),
('F', 17, 'quimica', '1', 'indisponivel'),
('F', 18, 'quimica', '1', 'indisponivel'),
('F', 19, 'quimica', '1', 'indisponivel'),
('F', 20, 'quimica', '1', 'indisponivel'),
('G', 1, 'nutricao', '1', 'disponivel'),
('G', 2, 'nutricao', '1', 'disponivel'),
('G', 3, 'nutricao', '1', 'disponivel'),
('G', 4, 'nutricao', '1', 'disponivel'),
('G', 5, 'nutricao', '1', 'disponivel'),
('G', 6, 'nutricao', '1', 'disponivel'),
('G', 7, 'nutricao', '1', 'disponivel'),
('G', 8, 'nutricao', '1', 'disponivel'),
('G', 9, 'nutricao', '1', 'disponivel'),
('G', 10, 'nutricao', '1', 'disponivel'),
('G', 11, 'nutricao', '1', 'disponivel'),
('G', 12, 'nutricao', '1', 'disponivel'),
('G', 13, 'nutricao', '1', 'disponivel'),
('G', 14, 'nutricao', '1', 'disponivel'),
('G', 15, 'nutricao', '1', 'disponivel'),
('G', 16, 'nutricao', '1', 'disponivel'),
('G', 17, 'nutricao', '1', 'disponivel'),
('G', 18, 'nutricao', '1', 'disponivel'),
('G', 19, 'nutricao', '1', 'disponivel'),
('G', 20, 'nutricao', '1', 'disponivel'),
('H', 1, 'nutricao', '1', 'disponivel'),
('H', 2, 'nutricao', '1', 'disponivel'),
('H', 3, 'nutricao', '1', 'disponivel'),
('H', 4, 'nutricao', '1', 'disponivel'),
('H', 5, 'nutricao', '1', 'disponivel'),
('H', 6, 'nutricao', '1', 'disponivel'),
('H', 7, 'nutricao', '1', 'disponivel'),
('H', 8, 'nutricao', '1', 'disponivel'),
('H', 9, 'nutricao', '1', 'disponivel'),
('H', 10, 'nutricao', '1', 'disponivel'),
('H', 11, 'nutricao', '1', 'disponivel'),
('H', 12, 'nutricao', '1', 'disponivel'),
('H', 13, 'nutricao', '1', 'disponivel'),
('H', 14, 'nutricao', '1', 'disponivel'),
('H', 15, 'nutricao', '1', 'disponivel'),
('H', 16, 'nutricao', '1', 'disponivel'),
('H', 17, 'nutricao', '1', 'disponivel'),
('H', 18, 'nutricao', '1', 'disponivel'),
('H', 19, 'nutricao', '1', 'disponivel'),
('H', 20, 'nutricao', '1', 'disponivel'),
('I', 1, 'nutricao', '1', 'indisponivel'),
('I', 2, 'nutricao', '1', 'indisponivel'),
('I', 3, 'nutricao', '1', 'indisponivel'),
('I', 4, 'nutricao', '1', 'indisponivel'),
('I', 5, 'nutricao', '1', 'indisponivel'),
('I', 6, 'nutricao', '1', 'indisponivel'),
('I', 7, 'nutricao', '1', 'indisponivel'),
('I', 8, 'nutricao', '1', 'indisponivel'),
('I', 9, 'nutricao', '1', 'indisponivel'),
('I', 10, 'nutricao', '1', 'indisponivel'),
('I', 11, 'nutricao', '1', 'indisponivel'),
('I', 12, 'nutricao', '1', 'indisponivel'),
('I', 13, 'nutricao', '1', 'indisponivel'),
('I', 14, 'nutricao', '1', 'indisponivel'),
('I', 15, 'nutricao', '1', 'indisponivel'),
('I', 16, 'nutricao', '1', 'indisponivel'),
('I', 17, 'nutricao', '1', 'indisponivel'),
('I', 18, 'nutricao', '1', 'indisponivel'),
('I', 19, 'nutricao', '1', 'indisponivel'),
('I', 20, 'nutricao', '1', 'indisponivel'),
('J', 1, 'nutricao', '1', 'alugado'),
('J', 2, 'nutricao', '1', 'alugado'),
('J', 3, 'nutricao', '1', 'alugado'),
('J', 4, 'nutricao', '1', 'alugado'),
('J', 5, 'nutricao', '1', 'alugado'),
('J', 6, 'nutricao', '1', 'alugado'),
('J', 7, 'nutricao', '1', 'alugado'),
('J', 8, 'nutricao', '1', 'alugado'),
('J', 9, 'nutricao', '1', 'alugado'),
('J', 10, 'nutricao', '1', 'alugado'),
('J', 11, 'nutricao', '1', 'alugado'),
('J', 12, 'nutricao', '1', 'alugado'),
('J', 13, 'nutricao', '1', 'alugado'),
('J', 14, 'nutricao', '1', 'alugado'),
('J', 15, 'nutricao', '1', 'alugado'),
('J', 16, 'nutricao', '1', 'alugado'),
('J', 17, 'nutricao', '1', 'alugado'),
('J', 18, 'nutricao', '1', 'alugado'),
('J', 19, 'nutricao', '1', 'alugado'),
('J', 20, 'nutricao', '1', 'alugado'),
('L', 1, 'administracao', '0', 'disponivel'),
('L', 2, 'administracao', '0', 'disponivel'),
('L', 3, 'administracao', '0', 'disponivel'),
('L', 4, 'administracao', '0', 'disponivel'),
('L', 5, 'administracao', '0', 'disponivel'),
('L', 6, 'administracao', '0', 'disponivel'),
('L', 7, 'administracao', '0', 'disponivel'),
('L', 8, 'administracao', '0', 'disponivel'),
('L', 9, 'administracao', '0', 'disponivel'),
('L', 10, 'administracao', '0', 'disponivel'),
('L', 11, 'administracao', '0', 'disponivel'),
('L', 12, 'administracao', '0', 'disponivel'),
('L', 13, 'administracao', '0', 'disponivel'),
('L', 14, 'administracao', '0', 'disponivel'),
('L', 15, 'administracao', '0', 'disponivel'),
('L', 16, 'administracao', '0', 'disponivel'),
('L', 17, 'administracao', '0', 'disponivel'),
('L', 18, 'administracao', '0', 'disponivel'),
('L', 19, 'administracao', '0', 'disponivel'),
('L', 20, 'administracao', '0', 'disponivel'),
('M', 1, 'administracao', '0', 'disponivel'),
('M', 2, 'administracao', '0', 'disponivel'),
('M', 3, 'administracao', '0', 'disponivel'),
('M', 4, 'administracao', '0', 'disponivel'),
('M', 5, 'administracao', '0', 'disponivel'),
('M', 6, 'administracao', '0', 'disponivel'),
('M', 7, 'administracao', '0', 'disponivel'),
('M', 8, 'administracao', '0', 'disponivel'),
('M', 9, 'administracao', '0', 'disponivel'),
('M', 10, 'administracao', '0', 'disponivel'),
('M', 11, 'administracao', '0', 'disponivel'),
('M', 12, 'administracao', '0', 'disponivel'),
('M', 13, 'administracao', '0', 'disponivel'),
('M', 14, 'administracao', '0', 'disponivel'),
('M', 15, 'administracao', '0', 'disponivel'),
('M', 16, 'administracao', '0', 'disponivel'),
('M', 17, 'administracao', '0', 'disponivel'),
('M', 18, 'administracao', '0', 'disponivel'),
('M', 19, 'administracao', '0', 'disponivel'),
('M', 20, 'administracao', '0', 'disponivel'),
('N', 1, 'administracao', '0', 'alugado'),
('N', 2, 'administracao', '0', 'alugado'),
('N', 3, 'administracao', '0', 'alugado'),
('N', 4, 'administracao', '0', 'alugado'),
('N', 5, 'administracao', '0', 'alugado'),
('N', 6, 'administracao', '0', 'alugado'),
('N', 7, 'administracao', '0', 'alugado'),
('N', 8, 'administracao', '0', 'alugado'),
('N', 9, 'administracao', '0', 'alugado'),
('N', 10, 'administracao', '0', 'alugado'),
('N', 11, 'administracao', '0', 'alugado'),
('N', 12, 'administracao', '0', 'alugado'),
('N', 13, 'administracao', '0', 'alugado'),
('N', 14, 'administracao', '0', 'alugado'),
('N', 15, 'administracao', '0', 'alugado'),
('N', 16, 'administracao', '0', 'alugado'),
('N', 17, 'administracao', '0', 'alugado'),
('N', 18, 'administracao', '0', 'alugado'),
('N', 19, 'administracao', '0', 'alugado'),
('N', 20, 'administracao', '0', 'alugado'),
('O', 1, 'administracao', '0', 'indisponivel'),
('O', 2, 'administracao', '0', 'indisponivel'),
('O', 3, 'administracao', '0', 'indisponivel'),
('O', 4, 'administracao', '0', 'indisponivel'),
('O', 5, 'administracao', '0', 'indisponivel'),
('O', 6, 'administracao', '0', 'indisponivel'),
('O', 7, 'administracao', '0', 'indisponivel'),
('O', 8, 'administracao', '0', 'indisponivel'),
('O', 9, 'administracao', '0', 'indisponivel'),
('O', 10, 'administracao', '0', 'indisponivel'),
('O', 11, 'administracao', '0', 'indisponivel'),
('O', 12, 'administracao', '0', 'indisponivel'),
('O', 13, 'administracao', '0', 'indisponivel'),
('O', 14, 'administracao', '0', 'indisponivel'),
('O', 15, 'administracao', '0', 'indisponivel'),
('O', 16, 'administracao', '0', 'indisponivel'),
('O', 17, 'administracao', '0', 'indisponivel'),
('O', 18, 'administracao', '0', 'indisponivel'),
('O', 19, 'administracao', '0', 'indisponivel'),
('O', 20, 'administracao', '0', 'indisponivel'),
('B', 1, 'quimica', '0', 'indisponivel'),
('B', 2, 'quimica', '0', 'indisponivel'),
('B', 3, 'quimica', '0', 'indisponivel'),
('B', 4, 'quimica', '0', 'indisponivel'),
('B', 5, 'quimica', '0', 'indisponivel'),
('B', 6, 'quimica', '0', 'indisponivel'),
('B', 7, 'quimica', '0', 'indisponivel'),
('B', 8, 'quimica', '0', 'indisponivel'),
('B', 9, 'quimica', '0', 'indisponivel'),
('B', 10, 'quimica', '0', 'indisponivel'),
('B', 11, 'quimica', '0', 'indisponivel'),
('B', 12, 'quimica', '0', 'indisponivel'),
('B', 13, 'quimica', '0', 'indisponivel'),
('B', 14, 'quimica', '0', 'indisponivel'),
('B', 15, 'quimica', '0', 'indisponivel'),
('B', 16, 'quimica', '0', 'indisponivel'),
('B', 17, 'quimica', '0', 'indisponivel'),
('B', 18, 'quimica', '0', 'indisponivel'),
('B', 19, 'quimica', '0', 'indisponivel');
